using UnityEngine;



namespace EMX.HierarchyPlugin.Editor
{

	partial class EditorSettingsAdapter
	{


		

		internal int BOOKMARKS_FOLDER_DEFAULT_ICON_SIZE { get { return GET("BOOKMARKS_FOLDER_DEFAULT_ICON_SIZE", 16); } set {var r = BOOKMARKS_FOLDER_DEFAULT_ICON_SIZE; SET( "BOOKMARKS_FOLDER_DEFAULT_ICON_SIZE", value); } }
		internal int BOOKMARKS_FOLDER_FONTSIZE { get { return GET("BOOKMARKS_FOLDER_FONTSIZE", 11); } set {var r = BOOKMARKS_FOLDER_FONTSIZE; SET( "BOOKMARKS_FOLDER_FONTSIZE", value); } }
		internal int BOOKMARKS_FOLDER_LINE_HEIGHT { get { return GET("BOOKMARKS_FOLDER_LINE_HEIGHT", 20); } set {var r = BOOKMARKS_FOLDER_LINE_HEIGHT; SET( "BOOKMARKS_FOLDER_LINE_HEIGHT", value); } }

		internal bool BOOKMARKS_FOLDER_SHOW_SELECTIONS { get { return false; } set {  } }
		internal bool BOOKMARKS_FOLDER_SHOW_ALL_DESCRIPTIONS_INHIER { get { return GET("BOOKMARKS_FOLDER_SHOW_ALL_DESCRIPTIONS_INHIER", true); } set {var r = BOOKMARKS_FOLDER_SHOW_ALL_DESCRIPTIONS_INHIER; SET( "BOOKMARKS_FOLDER_SHOW_ALL_DESCRIPTIONS_INHIER", value); } }
		internal bool BOOKMARKS_FOLDER_DRAW_BG_COLOR { get { return GET("BOOKMARKS_FOLDER_DRAW_BG_COLOR", true); } set {var r = BOOKMARKS_FOLDER_DRAW_BG_COLOR; SET( "BOOKMARKS_FOLDER_DRAW_BG_COLOR", value); } }
		internal Color BOOKMARKS_FOLDER_DEFULT_BG_COLOR { get { return GET("BOOKMARKS_FOLDER_DEFULT_BG_COLOR", Color.white); } set {var r = BOOKMARKS_FOLDER_DEFULT_BG_COLOR; SET( "BOOKMARKS_FOLDER_DEFULT_BG_COLOR", value); } }

	}
}
