namespace EMX.HierarchyPlugin.Editor
{

	partial class EditorSettingsAdapter
	{

		//0-simple mono ; 1-first char of name ; 2-two first chars of name
		internal int COMPONENTS_MONO_ICON_TYPE { get { return GET( "COMPONENTS_MONO_ICON_TYPE", 1 ); } set { var r = COMPONENTS_MONO_ICON_TYPE; SET( "COMPONENTS_MONO_ICON_TYPE", value ); p.RESET_DRAWSTACK( 0 ); } }

		internal bool COMPONENTS_CHANGE_MOUSE_CURSOR { get { return GET( "COMPONENTS_CHANGE_MOUSE_CURSOR", false ); } set { var r = COMPONENTS_CHANGE_MOUSE_CURSOR; SET( "COMPONENTS_CHANGE_MOUSE_CURSOR", value ); p.RESET_DRAWSTACK( 0 ); } }

		internal bool COMPONENTS_DRAW_ICONS_SHADOW { get { return GET( "COMPONENTS_DRAW_ICONS_SHADOW", false ); } set { var r = COMPONENTS_DRAW_ICONS_SHADOW; SET( "COMPONENTS_DRAW_ICONS_SHADOW", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal int COMPONENTS_MONO_SPLIT_MODE { get { return GET( "COMPONENTS_MONO_SPLIT_MODE", 0 ); } set { var r = COMPONENTS_MONO_SPLIT_MODE; SET( "COMPONENTS_MONO_SPLIT_MODE", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal int COMPONENTS_ICONS_SPACE { get { return GET( "COMPONENTS_ICONS_SPACE", -1 ); } set { var r = COMPONENTS_ICONS_SPACE; SET( "COMPONENTS_ICONS_SPACE", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal int COMPONENTS_ICONS_CAT_SPACE { get { return GET( "COMPONENTS_ICONS_CAT_SPACE", 2 ); } set { var r = COMPONENTS_ICONS_CAT_SPACE; SET( "COMPONENTS_ICONS_CAT_SPACE", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal int COMPONENTS_ICONS_SIZE { get { return GET( "COMPONENTS_ICONS_SIZE", 10 ); } set { var r = COMPONENTS_ICONS_SIZE; SET( "COMPONENTS_ICONS_SIZE", value ); p.RESET_DRAWSTACK( 0 ); } }

		internal bool COMPONENTS_CLAMP_GRAPHIC { get { return GET( "COMPONENTS_CLAMP_GRAPHIC", false ); } set { var r = COMPONENTS_CLAMP_GRAPHIC; SET( "COMPONENTS_CLAMP_GRAPHIC", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_CLAMP_EVENTS {

			get {
				if ( RIGHTDOCK_SHRINK_BUTTONS_INT < 2 ) return GET( "COMPONENTS_CLAMP_EVENTS", true );
				else return GET( "COMPONENTS_CLAMP_EVENTS_RIGHT_B", false );
			}
			set {
				var r = COMPONENTS_CLAMP_EVENTS;
				if ( RIGHTDOCK_SHRINK_BUTTONS_INT < 2 ) SET( "COMPONENTS_CLAMP_EVENTS", value );
				else SET( "COMPONENTS_CLAMP_EVENTS_RIGHT_B", value );
				p.RESET_DRAWSTACK( 0 );
			}
		}
		internal int COMPONENTS_DISABLED_CLAMP_OFFEST { get { return GET( "COMPONENTS_DISABLED_CLAMP_OFFEST", 6 ); } set { var r = COMPONENTS_DISABLED_CLAMP_OFFEST; SET( "COMPONENTS_DISABLED_CLAMP_OFFEST", value ); p.RESET_DRAWSTACK( 0 ); } }


		internal int COMPONENTS_NEXT_TO_NAME_PADDING { get { return GET( "COMPONENTS_NEXT_TO_NAME_PADDING", 10 ); } set { var r = COMPONENTS_NEXT_TO_NAME_PADDING; SET( "COMPONENTS_NEXT_TO_NAME_PADDING", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal int COMPONENTS_MARGIN_TOP { get { return GET( "COMPONENTS_MARGIN_TOP", 0 ); } set { var r = COMPONENTS_MARGIN_TOP; SET( "COMPONENTS_MARGIN_TOP", value ); p.RESET_DRAWSTACK( 0 ); } }

		internal bool COMPONENTS_DRAW_GLOBALCUSTOM_ICONS { get { return GET( "COMPONENTS_DRAW_GLOBALCUSTOM_ICONS", true ); } set { var r = COMPONENTS_DRAW_GLOBALCUSTOM_ICONS; SET( "COMPONENTS_DRAW_GLOBALCUSTOM_ICONS", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_DRAW_MONO_ICONS { get { return GET( "COMPONENTS_DRAW_MONO_ICONS", true ); } set { var r = COMPONENTS_DRAW_MONO_ICONS; SET( "COMPONENTS_DRAW_MONO_ICONS", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_DRAW_DEFAULT_ICONS { get { return GET( "COMPONENTS_DRAW_DEFAULT_ICONS", true ); } set { var r = COMPONENTS_DRAW_DEFAULT_ICONS; SET( "COMPONENTS_DRAW_DEFAULT_ICONS", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_DRAW_ICONS_MONO_BG_INVERSE { get { return !COMPONENTS_DRAW_ICONS_MONO_BG; } set { COMPONENTS_DRAW_ICONS_MONO_BG = !value; } }
		internal bool COMPONENTS_DRAW_ICONS_MONO_BG { get { return GET( "COMPONENTS_DRAW_ICONS_MONO_BG", true ); } set { var r = COMPONENTS_DRAW_ICONS_MONO_BG; SET( "COMPONENTS_DRAW_ICONS_MONO_BG", value ); p.RESET_DRAWSTACK( 0 ); } }

		internal bool COMPONENTS_DRAW_CUSTOM_ICONS_FROM_ISPECTOR { get { return GET( "COMPONENTS_DRAW_CUSTOM_ICONS_FROM_ISPECTOR", true ); } set { var r = COMPONENTS_DRAW_CUSTOM_ICONS_FROM_ISPECTOR; SET( "COMPONENTS_DRAW_CUSTOM_ICONS_FROM_ISPECTOR", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_DRAW_CUSTOM_ICONS_FROM_SETTINGS { get { return GET( "COMPONENTS_DRAW_CUSTOM_ICONS_FROM_SETTINGS", false ); } set { var r = COMPONENTS_DRAW_CUSTOM_ICONS_FROM_SETTINGS; SET( "COMPONENTS_DRAW_CUSTOM_ICONS_FROM_SETTINGS", value ); p.RESET_DRAWSTACK( 0 ); } }


		internal int COMPONENTS_ATTRIBUTES_MARGIN { get { return GET( "COMPONENTS_ATTRIBUTES_MARGIN", 6 ); } set { var r = COMPONENTS_ATTRIBUTES_MARGIN; SET( "COMPONENTS_ATTRIBUTES_MARGIN", value ); p.RESET_DRAWSTACK( 0 ); } }

		internal bool COMPONENTS_ATTRIBUTES_NAME_FOR_BUTTONS {
			get { return GET( "COMPONENTS_ATTRIBUTES_NAME_FOR_BUTTONS", true ); }
			set {
				var r = COMPONENTS_ATTRIBUTES_NAME_FOR_BUTTONS; SET( "COMPONENTS_ATTRIBUTES_NAME_FOR_BUTTONS", value );
				p.RESET_DRAWSTACK( 0 );
			}
		}
		internal bool COMPONENTS_ATTRIBUTES_BUTTONS { get { return GET( "COMPONENTS_ATTRIBUTES_BUTTONS", true ); } set { var r = COMPONENTS_ATTRIBUTES_BUTTONS; SET( "COMPONENTS_ATTRIBUTES_BUTTONS", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_ATTRIBUTES_FIELDS { get { return GET( "COMPONENTS_ATTRIBUTES_FIELDS", true ); } set { var r = COMPONENTS_ATTRIBUTES_FIELDS; ; SET( "COMPONENTS_ATTRIBUTES_FIELDS", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_ATTRIBUTES_DISPLAYING_NULLSISRED { get { return GET( "COMPONENTS_ATTRIBUTES_DISPLAYING_NULLSISRED", false ); } set { var r = COMPONENTS_ATTRIBUTES_DISPLAYING_NULLSISRED; SET( "COMPONENTS_ATTRIBUTES_DISPLAYING_NULLSISRED", value ); p.RESET_DRAWSTACK( 0 ); } }

		internal bool COMPONENTS_MENU_INCLUDEONLYMONOSCRIPTS { get { return GET( "COMPONENTS_MENU_INCLUDEONLYMONOSCRIPTS", false ); } set { var r = COMPONENTS_MENU_INCLUDEONLYMONOSCRIPTS; SET( "COMPONENTS_MENU_INCLUDEONLYMONOSCRIPTS", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_MENU_INCLUDESTATICFIELDS { get { return GET( "COMPONENTS_MENU_INCLUDESTATICFIELDS", true ); } set { var r = COMPONENTS_MENU_INCLUDESTATICFIELDS; SET( "COMPONENTS_MENU_INCLUDESTATICFIELDS", value ); p.RESET_DRAWSTACK( 0 ); } }
		internal bool COMPONENTS_MENU_INCLUDEBASECLASES { get { return GET( "COMPONENTS_MENU_INCLUDEBASECLASES", true ); } set { var r = COMPONENTS_MENU_INCLUDEBASECLASES; SET( "COMPONENTS_MENU_INCLUDEBASECLASES", value ); p.RESET_DRAWSTACK( 0 ); } }


		//   internal bool SAVE_HIGHLIGHTER_SETS_TO_HIDENFOLDER { get { return GET( "SAVE_HIGHLIGHTER_SETS_TO_HIDENFOLDER", false ); } set {var r = qwe; SET( "SAVE_HIGHLIGHTER_SETS_TO_HIDENFOLDER", value ); } }

	}



}
